### ISSUE TITLE
Utilidade de `ptBR-2013-10-30AOC-2`

### ISSUE THREAD

**Issue by filipemeneses** [hiyoku/FaTeX#1]
Legal o trabalho que vocês fizeram aqui. 👍 

Estou reorganizando o projeto em um fork aqui. Só não encontrei utilidade para os arquivos na pasta `ptBR-2013-10-30AOC-2`. Tem alguma razão deles estarem no projeto?

**Comment by hiyoku** [comment]
Opa! Muito obrigado.
Essa pasta contém os arquivos de dicionário (arquivos .dic) para o TexMaker ou o TexStudio a fim de corrigir as palavras escritas erradas, fiquei meio na dúvida entre colocar ou não, então optei por colocar.

Eu particularmente utilizei bastante, porque meu teclado é en-us, então tive dificuldades com acentos e tudo mais.

**Comment by filipemeneses** [comment]
Hmm, entendi. Imaginei que era arquivo para carregar em algum programa. Vou tirar do fork, deixar que quem for usar o FaTeX decida isso. haha

Também uso teclado en-us, dependendo do OS tem uns atalhos para acentuação (ex.: alt/option+e). Se tu usar Atom, tem um plugin para correção de gramática em pt-br que ajuda bastante.
